{{- if and .Values.messageBus.enabled .Values.messageBus.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kmp-supply-chain.fullname" . }}-message-bus-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kmp-supply-chain.labels" . | nindent 4 }}
    app.kubernetes.io/component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kmp-supply-chain.fullname" . }}-message-bus
  minReplicas: {{ .Values.messageBus.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.messageBus.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.messageBus.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.messageBus.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.messageBus.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.messageBus.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
{{- end }} 