{{- if .Values.security.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kmp-supply-chain.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kmp-supply-chain.labels" . | nindent 4 }}
    app.kubernetes.io/component: configuration
type: Opaque
data:
  database-url: {{ include "kmp-supply-chain.databaseUrl" . | b64enc }}
  jwt-secret: {{ .Values.security.secrets.jwtSecret | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kmp-supply-chain.fullname" . }}-wallet-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kmp-supply-chain.labels" . | nindent 4 }}
    app.kubernetes.io/component: blockchain
type: Opaque
data:
  mnemonic: {{ .Values.security.secrets.walletMnemonic | b64enc }}
  address: {{ .Values.security.secrets.walletAddress | b64enc }}
{{- end }} 