apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kmp-postgres-pvc
  namespace: kmp-supply-chain
  labels:
    app: kmp-postgres
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kmp-storage
  namespace: kmp-supply-chain
  labels:
    app: kmp-message-bus
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kmp-logs
  namespace: kmp-supply-chain
  labels:
    app: kmp-message-bus
    component: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard 